=== drozas/aw/p0/Practica1.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--Generated by Turbo XML 2.3.1.100. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
	 elementFormDefault = "qualified">
	<xsd:element name = "CorporateNet">
		<xsd:complexType>
			<xsd:choice minOccurs = "0" maxOccurs = "unbounded">
				<xsd:element ref = "Usuario"/>
				<xsd:element ref = "Aplicacion"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Usuario">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "Perfil" minOccurs = "0"/>
				<xsd:element ref = "Contacto" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Aplicacion">
		<xsd:complexType>
			<xsd:choice minOccurs = "0">
				<xsd:element ref = "InfoEmail"/>
				<xsd:element ref = "InfoBusqueda"/>
			</xsd:choice>
			<xsd:attribute name = "nombre" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "icono" use = "required" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Perfil">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "DatosPersonales"/>
				<xsd:element ref = "DatosProfesionales"/>
				<xsd:element ref = "Documento" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "DatosPersonales">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "FechaNacimiento"/>
			</xsd:sequence>
			<xsd:attribute name = "nombre" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "apellido" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "ciudad" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "codigoPostal" use = "required" type = "xsd:integer"/>
			<xsd:attribute name = "pais" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "fotografia" use = "required" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "DatosProfesionales">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "Interes" minOccurs = "0" maxOccurs = "unbounded"/>
				<xsd:element ref = "RedSocial" maxOccurs = "unbounded"/>
			</xsd:sequence>
			<xsd:attribute name = "empresa" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "ficheroCV" type = "xsd:string"/>
			<xsd:attribute name = "puesto" use = "required" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Interes">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base = "xsd:string">
					<xsd:attribute name = "tipoInteres" use = "required">
						<xsd:simpleType>
							<xsd:restriction base = "xsd:anyURI">
								<xsd:enumeration value = "Profesional"/>
								<xsd:enumeration value = "Investigador"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "RedSocial" type = "xsd:string"/>
	<xsd:element name = "FechaNacimiento">
		<xsd:complexType>
			<xsd:attribute name = "mes" use = "required">
				<xsd:simpleType>
					<xsd:restriction base = "xsd:integer">
						<xsd:maxInclusive value = "12"/>
						<xsd:minInclusive value = "1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name = "dia" use = "required">
				<xsd:simpleType>
					<xsd:restriction base = "xsd:integer">
						<xsd:maxInclusive value = "31"/>
						<xsd:minInclusive value = "1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name = "aÃ±o" use = "required">
				<xsd:simpleType>
					<xsd:restriction base = "xsd:integer">
						<xsd:minInclusive value = "1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Documento">
		<xsd:complexType>
			<xsd:attribute name = "privilegio" use = "required" type = "xsd:boolean"/>
			<xsd:attribute name = "tipoDocumento" use = "required">
				<xsd:simpleType>
					<xsd:restriction base = "xsd:string">
						<xsd:enumeration value = "WORD"/>
						<xsd:enumeration value = "PDF"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name = "path" use = "required" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "InfoEmail">
		<xsd:complexType>
			<xsd:attribute name = "mensaje" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "usuarioDestino" use = "required" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "InfoBusqueda">
		<xsd:complexType>
			<xsd:attribute name = "nombreUsuario" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "apellidoUsuario" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "red" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "Contacto">
		<xsd:complexType>
			<xsd:attribute name = "nombre" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "email" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "puesto" use = "required" type = "xsd:string"/>
			<xsd:attribute name = "red" use = "required" type = "xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== drozas/aw/p0/Practica1.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<CorporateNet xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "file:///Z:/AW/Practica1.xsd">
	<Aplicacion nombre = "Perfil" icono = "img/iconoPerfil">
	</Aplicacion>
	<Aplicacion nombre = "Contactos" icono = "img/iconoBuzon">
		<InfoEmail mensaje = "mensaje" usuarioDestino = "Antonio"/>
	</Aplicacion>
	<Aplicacion nombre = "Documentos" icono = "img/iconoBuzon">
		<InfoEmail mensaje = "mensaje" usuarioDestino = "Antonio"/>
	</Aplicacion>
	<Aplicacion nombre = "Buzon" icono = "img/iconoBuzon">
		<InfoEmail mensaje = "mensaje" usuarioDestino = "Antonio"/>
	</Aplicacion>
	<Aplicacion nombre = "Buscador" icono = "img/iconoBuscador">
		<InfoBusqueda nombreUsuario = "Antonio" apellidoUsuario = "Alvarez"/>
	</Aplicacion>
	
	<Usuario>
		<Perfil>
			<DatosPersonales nombre = "Antonio" apellido = "Alvarez Huerta" ciudad = "Mostoles" codigoPostal = "28936" pais = "España" fotografia = "">
				<FechaNacimiento mes = "12" dia = "9" año = "1984"/>
			</DatosPersonales>
			<DatosProfesionales empresa = "Telefonica" puesto = "Becario"/>
		</Perfil>
	</Usuario>
</CorporateNet>

=== drozas/aw/p1/Usuario1.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<CorporateNet xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "file:///Z:/AW/Practica/Practica1.xsd">
	<Aplicacion nombre = "Perfil" icono = "img/icons/perfil.gif"/>
	<Aplicacion nombre = "Contactos" icono = "img/icons/contactos.gif"/>
	<Aplicacion nombre = "Documentos" icono = "img/icons/documentos.gif"/>
	<Aplicacion nombre = "Buzon" icono = "img/icons/buzon.gif">
		<InfoEmail mensaje = "Hola, ¿qué tal?" usuarioDestino = "Antonio"/>
	</Aplicacion>
	<Aplicacion nombre = "Buscador" icono = "img/icons/buscador.gif">
		<InfoBusqueda nombreUsuario = "Antonio" apellidoUsuario = "Alvarez Huerta"/>
	</Aplicacion>
	<Usuario>
		<Perfil>
			<DatosPersonales nombre = "David" apellido = "Rozas Domingo" ciudad = "Alcorcón" codigoPostal = "28945" pais = "España" fotografia = "">
				<FechaNacimiento mes = "3" dia = "14" año = "1984"/>
			</DatosPersonales>
			<DatosProfesionales empresa = "ChurroSoft" puesto = "Precario" ficheroCV = "data/cv/davidRozas.pdf">
				<Interes tipoInteres = "Investigador">Aplicaciones Web</Interes>
				<Interes tipoInteres = "Investigador">Software Libre</Interes>
				<RedSocial>Tuenti</RedSocial>
			</DatosProfesionales>
			<Documento privilegio = "true" tipoDocumento = "WORD" path = "data/document/traspas.doc"/>
			<Documento privilegio = "false" tipoDocumento = "PDF" path = "data/document/pfc.pdf"/>
		</Perfil>
		<Contacto nombre = "Ivan Baltasar" email = "rsajor@gmail.com" puesto = "Directivo" red = "Facebook"/>
		<Contacto nombre = "Antonio Alvarez" email = "aah@tid.es" puesto = "Becario" red = "Tuenti"/>
		<Contacto nombre = "Bender Humo" email = "bender@robot.es" puesto = "Doblar Hierro" red = "Robotbook"/>
		<Contacto nombre = "Sofia Loren" email = "sofi_69@yahoo.es" puesto = "LaCalle" red = "Cyber"/>

	</Usuario>
</CorporateNet>
